// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5U6WfRX3wUHHCgUc2_M6eo4P67YLsd9M',
    appId: '1:448029162337:web:df7865c9ebf798c432a320',
    messagingSenderId: '448029162337',
    projectId: 'gratimate-6ba10',
    authDomain: 'gratimate-6ba10.firebaseapp.com',
    databaseURL: 'https://gratimate-6ba10-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gratimate-6ba10.firebasestorage.app',
    measurementId: 'G-BPQ0D17Q4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnrpekThyUKl9HJ54XGyfaKh7-eV1DRu8',
    appId: '1:448029162337:android:0bc53fb1877552a632a320',
    messagingSenderId: '448029162337',
    projectId: 'gratimate-6ba10',
    databaseURL: 'https://gratimate-6ba10-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gratimate-6ba10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXRY_Hq-_65FPiFNQk2TUkCwTKghdPfR8',
    appId: '1:448029162337:ios:98cdbe57b092128032a320',
    messagingSenderId: '448029162337',
    projectId: 'gratimate-6ba10',
    databaseURL: 'https://gratimate-6ba10-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gratimate-6ba10.firebasestorage.app',
    iosBundleId: 'com.riyadmazari.gratiMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXRY_Hq-_65FPiFNQk2TUkCwTKghdPfR8',
    appId: '1:448029162337:ios:98cdbe57b092128032a320',
    messagingSenderId: '448029162337',
    projectId: 'gratimate-6ba10',
    databaseURL: 'https://gratimate-6ba10-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gratimate-6ba10.firebasestorage.app',
    iosBundleId: 'com.riyadmazari.gratiMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5U6WfRX3wUHHCgUc2_M6eo4P67YLsd9M',
    appId: '1:448029162337:web:29d4aefed557980c32a320',
    messagingSenderId: '448029162337',
    projectId: 'gratimate-6ba10',
    authDomain: 'gratimate-6ba10.firebaseapp.com',
    databaseURL: 'https://gratimate-6ba10-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gratimate-6ba10.firebasestorage.app',
    measurementId: 'G-1YXQKG240E',
  );

}